### ISSUE TITLE
Data does not persist when Block is moved

### ISSUE THREAD

**Issue by supercrafter100** [JEFF-Media-GbR/CustomBlockData#11]
When using this on 1.20.1, the data does not seem to persist when the block gets moved. I've tried using the example plugin but I cannot seem to build it anymore. The dependency in it's pom is outdated and modifying it to the newer version just causes mismatching imports which I really don't want to fix.

I'm setting the container on a block of TNT, then requesting the data when it gets ignited during the TNTPrimeEvent. The data doesn't end up existing anymore when I retrieve it after it has been moved. When I retrieve it without the tnt moving at all from it's initial location, it still exists.

Code I use to set the data. I have confirmed this code is ran to set it.
```kotlin
val container = CustomBlockData(bukkitBlock, MissileWars.instance)
val key = NamespacedKey(MissileWars.instance, "owner")
container.set(key, PersistentDataType.STRING, user.player.uniqueId.toString())
```

Code I use to retrieve the data
```kotlin
@EventHandler
private fun onEntityIgnite(event: TNTPrimeEvent) {
    val block = event.block
    val container = CustomBlockData(block, MissileWars.instance)
    val key = NamespacedKey(MissileWars.instance, "owner")
    if (!container.has(key)) {
        return
    }

    val owner = container.get(key, PersistentDataType.STRING)!!
    // Additional code not relevant here
}
```

**Comment by supercrafter100** [comment]
![https://i.gyazo.com/080b8016d4d8f1eb709f5916426f928e.gif](https://i.gyazo.com/080b8016d4d8f1eb709f5916426f928e.gif)

**Comment by mfnalex** [comment]
You have to call CustomBlockData#registerListeners(Plugin) in your onEnable() method, then it should work fine

**Comment by supercrafter100** [comment]
I'll test it out tomorrow and keep you updated. Thanks for the quick response.

**Comment by mfnalex** [comment]
This is mentioned in the javadocs btw (https://hub.jeff-media.com/javadocs/customblockdata/) but I forgot to mention it in the readme. I‘ll fix the readme tomorrow, sorry for that.

**Comment by supercrafter100** [comment]
The addition of the line you mentioned seemed to have done the trick. Thank you!
